### ISSUE TITLE
FaceDetector feature crash immediately for all version above 1.1.4

### ISSUE THREAD

**Issue by tuannguyenhoangit** [react-native-community/react-native-camera#2189]
# Bug Report
**To Do First**
I have tried with a lot of version above 1.1.4  but all of them crash immediately
-----------
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RNSensorOrientationChecker", referenced from:
      objc-class-ref in libRNCamera.a(RNCamera.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
---------
I choose Non-Pod method by downloading 5 files, extract and import frameworks. It's working fine in 1.1.4 version. But that version doesn't have whiteBalance. I want to use whiteBalance feature.
